services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  usuario-service:
    build: ./usuario.service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/usuarios
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}


  producto-service:
    build: ./producto.service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/productos
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}


  pedido-service:
    build: ./pedido.service
    depends_on:
      postgres:
        condition: service_healthy
      usuario-service:
        condition: service_started
      producto-service:
        condition: service_started
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/pedidos
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    
  gateway-service:
    build: ./gateway-service
    depends_on:
      usuario-service:
        condition: service_started
      producto-service:
        condition: service_started
      pedido-service:
        condition: service_started
    ports:
      - "8080:8080"

volumes:
  postgres_data: