server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: http://usuario-service:8080
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/usuarios/(?<segment>.*), /usuarios/${segment}

        - id: producto-service
          uri: http://producto-service:8080
          predicates:
            - Path=/api/productos/**
          filters:
            - RewritePath=/api/productos/(?<segment>.*), /productos/${segment}

        - id: pedido-service
          uri: http://pedido-service:8080
          predicates:
            - Path=/api/pedidos/**
          filters:
            - RewritePath=/api/pedidos/(?<segment>.*), /pedido/${segment}